-- Exhale Academy Quiz MVP schema + RLS policies
-- Run this in Supabase SQL editor.

begin;

create extension if not exists pgcrypto;

-- Questions table (already exists in your project, included for safety)
create table if not exists public.questions (
  id uuid primary key default gen_random_uuid(),
  category text not null,
  sub_concept text,
  difficulty text,
  cognitive_level text,
  exam_priority text,
  stem text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_answer text not null,
  rationale_correct text,
  rationale_why_others_wrong jsonb,
  keywords_to_notice text[],
  common_trap text,
  exam_logic text,
  qa_summary text,
  created_at timestamptz default now()
);

-- Quiz session parent table
create table if not exists public.quiz_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  mode text not null check (mode in ('practice', 'exam')),
  total_questions integer not null check (total_questions > 0),
  created_at timestamptz not null default now()
);

create index if not exists quiz_sessions_user_id_idx on public.quiz_sessions(user_id);
create index if not exists quiz_sessions_created_at_idx on public.quiz_sessions(created_at desc);

-- Ordered list of questions for each session
create table if not exists public.quiz_session_questions (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.quiz_sessions(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete restrict,
  order_index integer not null,
  created_at timestamptz not null default now(),
  unique (session_id, order_index),
  unique (session_id, question_id)
);

create index if not exists quiz_session_questions_session_id_idx on public.quiz_session_questions(session_id);
create index if not exists quiz_session_questions_question_id_idx on public.quiz_session_questions(question_id);

-- Answers stored per question per session
create table if not exists public.quiz_answers (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.quiz_sessions(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete restrict,
  selected_answer text not null check (selected_answer in ('A', 'B', 'C', 'D')),
  is_correct boolean not null,
  answered_at timestamptz not null default now(),
  unique (session_id, question_id)
);

create index if not exists quiz_answers_session_id_idx on public.quiz_answers(session_id);
create index if not exists quiz_answers_question_id_idx on public.quiz_answers(question_id);

-- RLS
alter table public.questions enable row level security;
alter table public.quiz_sessions enable row level security;
alter table public.quiz_session_questions enable row level security;
alter table public.quiz_answers enable row level security;

-- Questions readable by authenticated users

drop policy if exists questions_select_authenticated on public.questions;
create policy questions_select_authenticated
on public.questions
for select
to authenticated
using (true);

-- quiz_sessions: users can only see and manage their own

drop policy if exists quiz_sessions_select_own on public.quiz_sessions;
create policy quiz_sessions_select_own
on public.quiz_sessions
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists quiz_sessions_insert_own on public.quiz_sessions;
create policy quiz_sessions_insert_own
on public.quiz_sessions
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists quiz_sessions_update_own on public.quiz_sessions;
create policy quiz_sessions_update_own
on public.quiz_sessions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists quiz_sessions_delete_own on public.quiz_sessions;
create policy quiz_sessions_delete_own
on public.quiz_sessions
for delete
to authenticated
using (auth.uid() = user_id);

-- quiz_session_questions policies via parent session ownership

drop policy if exists quiz_session_questions_select_own on public.quiz_session_questions;
create policy quiz_session_questions_select_own
on public.quiz_session_questions
for select
to authenticated
using (
  exists (
    select 1
    from public.quiz_sessions s
    where s.id = quiz_session_questions.session_id
      and s.user_id = auth.uid()
  )
);

drop policy if exists quiz_session_questions_insert_own on public.quiz_session_questions;
create policy quiz_session_questions_insert_own
on public.quiz_session_questions
for insert
to authenticated
with check (
  exists (
    select 1
    from public.quiz_sessions s
    where s.id = quiz_session_questions.session_id
      and s.user_id = auth.uid()
  )
);

drop policy if exists quiz_session_questions_update_own on public.quiz_session_questions;
create policy quiz_session_questions_update_own
on public.quiz_session_questions
for update
to authenticated
using (
  exists (
    select 1
    from public.quiz_sessions s
    where s.id = quiz_session_questions.session_id
      and s.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.quiz_sessions s
    where s.id = quiz_session_questions.session_id
      and s.user_id = auth.uid()
  )
);

drop policy if exists quiz_session_questions_delete_own on public.quiz_session_questions;
create policy quiz_session_questions_delete_own
on public.quiz_session_questions
for delete
to authenticated
using (
  exists (
    select 1
    from public.quiz_sessions s
    where s.id = quiz_session_questions.session_id
      and s.user_id = auth.uid()
  )
);

-- quiz_answers policies via parent session ownership

drop policy if exists quiz_answers_select_own on public.quiz_answers;
create policy quiz_answers_select_own
on public.quiz_answers
for select
to authenticated
using (
  exists (
    select 1
    from public.quiz_sessions s
    where s.id = quiz_answers.session_id
      and s.user_id = auth.uid()
  )
);

drop policy if exists quiz_answers_insert_own on public.quiz_answers;
create policy quiz_answers_insert_own
on public.quiz_answers
for insert
to authenticated
with check (
  exists (
    select 1
    from public.quiz_sessions s
    where s.id = quiz_answers.session_id
      and s.user_id = auth.uid()
  )
);

drop policy if exists quiz_answers_update_own on public.quiz_answers;
create policy quiz_answers_update_own
on public.quiz_answers
for update
to authenticated
using (
  exists (
    select 1
    from public.quiz_sessions s
    where s.id = quiz_answers.session_id
      and s.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.quiz_sessions s
    where s.id = quiz_answers.session_id
      and s.user_id = auth.uid()
  )
);

drop policy if exists quiz_answers_delete_own on public.quiz_answers;
create policy quiz_answers_delete_own
on public.quiz_answers
for delete
to authenticated
using (
  exists (
    select 1
    from public.quiz_sessions s
    where s.id = quiz_answers.session_id
      and s.user_id = auth.uid()
  )
);

commit;
