export type Flashcard = {
  id: string;
  front: string;
  back: string;
  section: string;
  frontImage?: string;
  frontImageAlt?: string;
};

export const mechanicalVentilationSections = [
  "Core Concepts",
  "Full Support Modes",
  "Partial Support Modes",
  "Spontaneous Modes",
  "Waveforms",
] as const;

export const mechanicalVentilationCards: Flashcard[] = [
  { id: "mv-what-is", section: "Core Concepts", front: "What is mechanical ventilation?", back: "The use of a ventilator to assist or fully take over the work of breathing." },
  { id: "mv-why-used", section: "Core Concepts", front: "Why is mechanical ventilation used?", back: "To help oxygenate and ventilate patients who cannot do it effectively on their own." },
  { id: "mv-indications", section: "Core Concepts", front: "When is mechanical ventilation indicated?", back: "When work of breathing is too high, the patient is apneic or hypoventilating, gas exchange is impaired, or surgery requires ventilatory support." },
  { id: "mv-goals", section: "Core Concepts", front: "What are the main goals of mechanical ventilation?", back: "Maintain oxygenation, maintain ventilation, reduce work of breathing, prevent or reverse respiratory failure, stabilize mechanics, and allow time for recovery." },
  { id: "mv-mode-selection", section: "Core Concepts", front: "Why does mode selection matter?", back: "It determines how much the ventilator assists, how breaths are triggered and cycled, and whether the patient can breathe spontaneously." },
  { id: "mv-mode-categories", section: "Core Concepts", front: "What are the 3 major mode categories?", back: "Full support, partial support, and spontaneous modes." },
  { id: "mv-full-support", section: "Core Concepts", front: "What is a full support mode?", back: "A mode where the ventilator does all or nearly all of the breathing work." },
  { id: "mv-partial-support", section: "Core Concepts", front: "What is a partial support mode?", back: "A mode that shares the breathing work between the ventilator and the patient." },
  { id: "mv-spontaneous-mode", section: "Core Concepts", front: "What is a spontaneous mode?", back: "A mode where the patient does the work of breathing and the ventilator offers limited assistance." },
  { id: "mv-trigger", section: "Core Concepts", front: "What is trigger on a ventilator?", back: "What starts the breath, either time or patient effort." },
  { id: "mv-cycle", section: "Core Concepts", front: "What is cycle on a ventilator?", back: "What ends the breath, such as volume, time, or flow." },
  { id: "mv-target", section: "Core Concepts", front: "What is target on a ventilator?", back: "What the ventilator is trying to control, such as pressure or volume." },

  { id: "acvc-name", section: "Full Support Modes", front: "What mode is AC/VC?", back: "Assist-Control Volume Control." },
  { id: "acvc-category", section: "Full Support Modes", front: "What category does AC/VC belong to?", back: "Full support." },
  { id: "acvc-trigger", section: "Full Support Modes", front: "What triggers a breath in AC/VC?", back: "Time or patient effort." },
  { id: "acvc-cycle", section: "Full Support Modes", front: "What cycles a breath in AC/VC?", back: "Volume." },
  { id: "acvc-target", section: "Full Support Modes", front: "What is the target in AC/VC?", back: "Volume." },
  { id: "acvc-how", section: "Full Support Modes", front: "How does AC/VC work?", back: "The vent delivers a preset tidal volume for every breath, whether patient-triggered or time-triggered." },
  { id: "acvc-uses", section: "Full Support Modes", front: "When is AC/VC a strong choice?", back: "Apnea, drug overdose, post-cardiac arrest, neuromuscular disorders, and ARDS." },
  { id: "acvc-settings", section: "Full Support Modes", front: "What adult settings were listed for AC/VC?", back: "Rate 12-20 bpm, VT 6-8 mL/kg IBW, start FiO2 high then titrate, PEEP 5 cmH2O." },
  { id: "acvc-alarms", section: "Full Support Modes", front: "What alarms matter in AC/VC?", back: "High pressure, low exhaled tidal volume, and apnea if the patient stops triggering." },
  { id: "acvc-pro", section: "Full Support Modes", front: "What is a main pro of AC/VC?", back: "Reliable full ventilatory support and consistent tidal volumes." },
  { id: "acvc-con", section: "Full Support Modes", front: "What is a main con of AC/VC?", back: "Risk of hyperventilation and respiratory alkalosis; it is not a weaning mode." },
  { id: "acpc-name", section: "Full Support Modes", front: "What mode is AC/PC?", back: "Assist-Control Pressure Control." },
  { id: "acpc-cycle", section: "Full Support Modes", front: "What cycles a breath in AC/PC?", back: "Time." },
  { id: "acpc-target", section: "Full Support Modes", front: "What is the target in AC/PC?", back: "Pressure." },
  { id: "acpc-how", section: "Full Support Modes", front: "How does AC/PC work?", back: "It delivers a set inspiratory pressure for a set inspiratory time, so volume varies with compliance and resistance." },
  { id: "acpc-uses", section: "Full Support Modes", front: "When is AC/PC useful?", back: "ARDS, stiff lungs, or status asthmaticus when pressure limitation matters." },
  { id: "acpc-settings", section: "Full Support Modes", front: "What adult settings were listed for AC/PC?", back: "Rate 12-20 bpm, PIP 15-25 cmH2O, I-time 0.8-1.2 sec, PEEP 5, FiO2 titrate down from a high start." },
  { id: "acpc-alarms", section: "Full Support Modes", front: "What alarms matter in AC/PC?", back: "Low tidal volume and high pressure." },
  { id: "acpc-pro", section: "Full Support Modes", front: "What is a main pro of AC/PC?", back: "It limits peak airway pressure and is more lung protective." },
  { id: "acpc-con", section: "Full Support Modes", front: "What is a main con of AC/PC?", back: "Delivered tidal volume varies, so minute ventilation must be watched closely." },
  { id: "prvc-name", section: "Full Support Modes", front: "What does PRVC stand for?", back: "Pressure Regulated Volume Control." },
  { id: "prvc-category", section: "Full Support Modes", front: "What category does PRVC belong to?", back: "Full support." },
  { id: "prvc-target", section: "Full Support Modes", front: "What is the target in PRVC?", back: "Volume, delivered by automatically adjusting pressure." },
  { id: "prvc-how", section: "Full Support Modes", front: "How does PRVC work?", back: "The vent targets a set tidal volume using the lowest pressure possible and adjusts pressure breath to breath." },
  { id: "prvc-uses", section: "Full Support Modes", front: "When is PRVC useful?", back: "ARDS, patients at risk for barotrauma, and patients with variable compliance." },
  { id: "prvc-pro", section: "Full Support Modes", front: "What is a main pro of PRVC?", back: "It combines volume targeting with pressure adjustment for lung protection." },
  { id: "prvc-con", section: "Full Support Modes", front: "What is a main con of PRVC?", back: "It can underdeliver volume if the pressure limit is too low." },
  { id: "aprv-name", section: "Full Support Modes", front: "What does APRV stand for?", back: "Airway Pressure Release Ventilation." },
  { id: "aprv-how", section: "Full Support Modes", front: "How does APRV work?", back: "It alternates between two CPAP levels, spending most of the time at high pressure to improve recruitment." },
  { id: "aprv-uses", section: "Full Support Modes", front: "When is APRV useful?", back: "ARDS, refractory hypoxemia, and patients needing high FiO2 or PEEP." },
  { id: "aprv-settings", section: "Full Support Modes", front: "What starting settings were listed for APRV?", back: "PHigh 20-30, PLow 0-5, THigh 4-6 sec, TLow 0.5-1 sec, FiO2 titrated to SpO2 goal." },
  { id: "aprv-pro", section: "Full Support Modes", front: "What is a main pro of APRV?", back: "Excellent oxygenation and alveolar recruitment with spontaneous breathing allowed." },
  { id: "aprv-con", section: "Full Support Modes", front: "What is a main con of APRV?", back: "It is complex to titrate and may cause CO2 retention or air trapping." },
  { id: "irv-name", section: "Full Support Modes", front: "What does IRV stand for?", back: "Inverse Ratio Ventilation." },
  { id: "irv-how", section: "Full Support Modes", front: "How does IRV work?", back: "It uses an inspiratory-to-expiratory ratio greater than 1:1 to raise mean airway pressure and improve oxygenation." },
  { id: "irv-uses", section: "Full Support Modes", front: "When is IRV used?", back: "ARDS or severe hypoxemia not responding to traditional settings." },
  { id: "irv-warning", section: "Full Support Modes", front: "What is a key warning for IRV?", back: "It may cause auto-PEEP or barotrauma and is usually used under heavy sedation or paralysis." },

  { id: "simvvc-name", section: "Partial Support Modes", front: "What mode is SIMV-VC?", back: "Synchronized Intermittent Mandatory Ventilation - Volume Control." },
  { id: "simvvc-how", section: "Partial Support Modes", front: "How does SIMV-VC work?", back: "The vent gives a set number of volume-controlled mandatory breaths, and the patient can breathe spontaneously between them." },
  { id: "simvvc-uses", section: "Partial Support Modes", front: "When is SIMV-VC useful?", back: "Weaning, post-op patients with improving drive, and sedation holidays." },
  { id: "simvvc-settings", section: "Partial Support Modes", front: "What adult settings were listed for SIMV-VC?", back: "Rate 6-14, VT 6-8 mL/kg IBW, FiO2 titrate, PEEP 5, and PS 5-12 if used." },
  { id: "simvvc-pro", section: "Partial Support Modes", front: "What is a main pro of SIMV-VC?", back: "It encourages use of the patient’s own respiratory muscles." },
  { id: "simvvc-con", section: "Partial Support Modes", front: "What is a main con of SIMV-VC?", back: "It can increase work of breathing and cause fatigue if support is inadequate." },
  { id: "simvpc-name", section: "Partial Support Modes", front: "What mode is SIMV-PC?", back: "Synchronized Intermittent Mandatory Ventilation - Pressure Control." },
  { id: "simvpc-how", section: "Partial Support Modes", front: "How does SIMV-PC work?", back: "It gives a set number of pressure-controlled mandatory breaths with spontaneous breaths in between." },
  { id: "simvpc-uses", section: "Partial Support Modes", front: "When is SIMV-PC useful?", back: "ARDS with a weaning plan, low-compliance lungs, and transition off AC/PC." },
  { id: "simvpc-pro", section: "Partial Support Modes", front: "What is a main pro of SIMV-PC?", back: "Less barotrauma than SIMV-VC and spontaneous breathing is allowed." },
  { id: "simvpc-con", section: "Partial Support Modes", front: "What is a main con of SIMV-PC?", back: "It can under-ventilate if the patient fatigues and spontaneous volumes fall." },
  { id: "simvprvc-name", section: "Partial Support Modes", front: "What is SIMV-PRVC?", back: "A hybrid mode that combines SIMV with PRVC logic to give mandatory breaths with volume targeting through pressure adjustment." },
  { id: "simvprvc-uses", section: "Partial Support Modes", front: "When is SIMV-PRVC useful?", back: "Variable lung mechanics, weaning with some volume consistency, and spontaneous efforts with lung protection." },
  { id: "simvprvc-pro", section: "Partial Support Modes", front: "What is a main pro of SIMV-PRVC?", back: "Mandatory breaths stay volume-targeted while pressure adjusts for protection." },
  { id: "simvprvc-con", section: "Partial Support Modes", front: "What is a main con of SIMV-PRVC?", back: "The interaction between spontaneous effort and volume targeting can be complex." },
  { id: "bilevel-name", section: "Partial Support Modes", front: "What is bilevel mode on the ventilator?", back: "A pressure-based mode that alternates between high and low pressure levels while allowing spontaneous breathing at both levels." },
  { id: "bilevel-uses", section: "Partial Support Modes", front: "When is bilevel useful?", back: "ARDS or hypoxemic respiratory failure, weaning from higher support, and improving comfort with spontaneous breathing." },
  { id: "bilevel-pro", section: "Partial Support Modes", front: "What is a main pro of bilevel ventilation?", back: "It supports oxygenation while still allowing spontaneous breathing." },
  { id: "bilevel-con", section: "Partial Support Modes", front: "What is a main con of bilevel ventilation?", back: "Settings can be complex and it is not available on all ventilators." },
  { id: "psv-name", section: "Partial Support Modes", front: "What is PSV?", back: "Pressure Support Ventilation." },
  { id: "psv-category", section: "Partial Support Modes", front: "What category does PSV belong to?", back: "Partial support." },
  { id: "psv-trigger", section: "Partial Support Modes", front: "What triggers a breath in PSV?", back: "Patient effort only." },
  { id: "psv-cycle", section: "Partial Support Modes", front: "What cycles a breath in PSV?", back: "Flow." },
  { id: "psv-how", section: "Partial Support Modes", front: "How does PSV work?", back: "Every breath is patient-initiated and supported by a preset pressure to reduce work of breathing." },
  { id: "psv-uses", section: "Partial Support Modes", front: "When is PSV useful?", back: "Weaning trials, minimal assistance, and spontaneous breathing trials." },
  { id: "psv-settings", section: "Partial Support Modes", front: "What settings were listed for PSV?", back: "PS 5-12, PEEP 5, FiO2 titrate, and no set mandatory rate." },
  { id: "psv-pro", section: "Partial Support Modes", front: "What is a main pro of PSV?", back: "It is excellent for weaning and improves comfort and synchrony." },
  { id: "psv-con", section: "Partial Support Modes", front: "What is a main con of PSV?", back: "There is no backup rate, so the patient must breathe." },

  { id: "cpappsv-name", section: "Spontaneous Modes", front: "What is CPAP/PSV?", back: "CPAP with Pressure Support, a spontaneous mode where CPAP keeps alveoli open and PS assists each spontaneous breath." },
  { id: "cpappsv-uses", section: "Spontaneous Modes", front: "When is CPAP/PSV useful?", back: "SBTs, weaning, extubation readiness, and stable respiratory drive." },
  { id: "cpappsv-warning", section: "Spontaneous Modes", front: "What is a key warning for CPAP/PSV?", back: "There is no backup mode unless separately enabled, so it is unsafe for apnea or unstable neurologic patients." },
  { id: "cpap-alone-name", section: "Spontaneous Modes", front: "What is CPAP alone on the vent?", back: "Continuous pressure without inspiratory pressure support." },
  { id: "cpap-alone-uses", section: "Spontaneous Modes", front: "When is CPAP alone useful?", back: "Final step before extubation, evaluating spontaneous effort, and alert patients with minimal secretions." },
  { id: "cpap-alone-pro", section: "Spontaneous Modes", front: "What is a main pro of CPAP alone?", back: "It is closest to normal breathing and tests true patient effort." },
  { id: "cpap-alone-con", section: "Spontaneous Modes", front: "What is a main con of CPAP alone?", back: "It can increase work of breathing and fatigue borderline patients." },
  { id: "nava-name", section: "Spontaneous Modes", front: "What does NAVA stand for?", back: "Neurally Adjusted Ventilatory Assist." },
  { id: "nava-how", section: "Spontaneous Modes", front: "How does NAVA work?", back: "It uses a catheter to detect diaphragm electrical activity and gives support proportional to patient effort." },
  { id: "nava-uses", section: "Spontaneous Modes", front: "When is NAVA useful?", back: "Asynchrony in traditional modes, neonates and pediatrics, ventilator dependency with poor synchrony, and some NIV cases." },
  { id: "nava-pro", section: "Spontaneous Modes", front: "What is a main pro of NAVA?", back: "It offers near-perfect synchrony and can reduce sedation needs." },
  { id: "nava-con", section: "Spontaneous Modes", front: "What is a main con of NAVA?", back: "It requires specialized equipment and has a learning curve." },

  { id: "waveform-image-vc", section: "Waveforms", front: "What type of waveform pattern is this?", back: "Volume Control.", frontImage: "/flashcards/mechanical-ventilation/vc-waveform.svg", frontImageAlt: "Volume control waveform identification flashcard" },
  { id: "waveform-image-pc", section: "Waveforms", front: "What type of waveform pattern is this?", back: "Pressure Control.", frontImage: "/flashcards/mechanical-ventilation/pc-waveform.svg", frontImageAlt: "Pressure control waveform identification flashcard" },
  { id: "waveform-vc-flow", section: "Waveforms", front: "What inspiratory flow pattern is common in volume control?", back: "Often constant or square flow." },
  { id: "waveform-pc-flow", section: "Waveforms", front: "What inspiratory flow pattern is common in pressure control?", back: "Descending flow." },
  { id: "waveform-acvc-clue", section: "Waveforms", front: "What is a common board clue for AC/VC?", back: "Set tidal volume every breath, whether time-triggered or patient-triggered." },
  { id: "waveform-acpc-clue", section: "Waveforms", front: "What is a common board clue for AC/PC?", back: "Pressure is fixed, but delivered volume changes with compliance and resistance." },
  { id: "waveform-prvc-clue", section: "Waveforms", front: "What is a common board clue for PRVC?", back: "Targeted volume with automatic pressure adjustment to use the lowest pressure possible." },
  { id: "waveform-aprv-clue", section: "Waveforms", front: "What is a common board clue for APRV?", back: "Two CPAP levels with most of the time spent at high pressure for alveolar recruitment." },
  { id: "waveform-psv-clue", section: "Waveforms", front: "What is a common board clue for PSV?", back: "The patient triggers every breath and there is no mandatory backup rate unless separately set." },
  { id: "support-when-full", section: "Waveforms", front: "When should full support modes be used?", back: "Apnea, paralysis, severe ARDS or hypoxemia, or when heavy sedation is required." },
  { id: "support-avoid-full", section: "Waveforms", front: "When should full support modes be avoided?", back: "When the patient is breathing well spontaneously or is already in a weaning phase." },
  { id: "support-when-partial", section: "Waveforms", front: "When should partial support modes be used?", back: "Improving respiratory drive, transition off full support, and weaning or testing spontaneous breathing." },
  { id: "support-avoid-partial", section: "Waveforms", front: "When should partial support modes be avoided?", back: "Apnea, heavy sedation, unstable acid-base status, excessive secretions, or poor spontaneous effort." },
  { id: "support-when-spont", section: "Waveforms", front: "When should spontaneous modes be used?", back: "Awake patients breathing on their own, spontaneous breathing trials, and extubation readiness." },
  { id: "support-avoid-spont", section: "Waveforms", front: "When should spontaneous modes be avoided?", back: "Altered mental status, apnea, hemodynamic instability, poor effort, or ongoing high work of breathing." },
];
