export type Flashcard = {
  id: string;
  front: string;
  back: string;
  section: string;
};

export const respiratoryDiseaseSections = [
  "Asthma",
  "COPD",
  "ARDS",
  "Cystic Fibrosis",
  "Pneumonia",
  "Tuberculosis",
  "Pulmonary Embolism",
  "Pulmonary Fibrosis",
  "Bronchiectasis",
] as const;

export const respiratoryDiseasePatternCards: Flashcard[] = [
  { id: "asthma-definition", section: "Asthma", front: "What is asthma?", back: "A chronic inflammatory airway disease with reversible bronchoconstriction." },
  { id: "asthma-triggers", section: "Asthma", front: "What commonly triggers asthma?", back: "Allergens, cold air, exercise, stress, and respiratory infections." },
  { id: "asthma-symptoms", section: "Asthma", front: "What symptoms should make you think asthma fast?", back: "Wheezing, cough, chest tightness, and shortness of breath." },
  { id: "asthma-diagnostic-clue", section: "Asthma", front: "What diagnostic clue supports asthma on the boards?", back: "Decreased FEV1 or peak flow that improves after bronchodilator therapy." },
  { id: "asthma-dlco", section: "Asthma", front: "What diffusion clue helps separate asthma from fibrosis?", back: "Asthma usually has a normal DLCO." },
  { id: "asthma-cxr", section: "Asthma", front: "What chest x-ray finding may appear during an asthma attack?", back: "Hyperinflation from air trapping." },
  { id: "asthma-rt", section: "Asthma", front: "What RT interventions matter most in asthma?", back: "Albuterol, oxygen if hypoxemic, steroids, reassessment, and inhaler teaching." },
  { id: "asthma-buzzword", section: "Asthma", front: "What board buzzword should make you think severe asthma?", back: "A quiet chest in a struggling patient suggests very poor airflow." },
  { id: "asthma-comparison", section: "Asthma", front: "How does asthma differ from COPD on exams?", back: "Asthma is usually reversible with bronchodilators; COPD is chronic and less reversible." },
  { id: "asthma-trap", section: "Asthma", front: "What is a common exam trap with asthma?", back: "Missing fatigue when PaCO2 rises or breath sounds become very diminished." },
  { id: "asthma-memory", section: "Asthma", front: "What quick memory trick helps you remember asthma?", back: "Asthma = obstructed but reversible." },

  { id: "copd-definition", section: "COPD", front: "What is COPD?", back: "A progressive obstructive disease that includes chronic bronchitis and emphysema." },
  { id: "copd-causes", section: "COPD", front: "What commonly causes COPD?", back: "Smoking, long-term irritant exposure, and alpha-1 antitrypsin deficiency." },
  { id: "copd-symptoms", section: "COPD", front: "What symptoms are high-yield for COPD?", back: "Chronic cough, sputum production, dyspnea, wheezing, and prolonged exhalation." },
  { id: "copd-spirometry", section: "COPD", front: "What spirometry finding supports COPD?", back: "An FEV1/FVC ratio below 70%." },
  { id: "copd-hyperinflation", section: "COPD", front: "What imaging clue supports emphysema-predominant COPD?", back: "Flattened diaphragms with hyperinflation." },
  { id: "copd-lung-volumes", section: "COPD", front: "What lung volume changes are common in COPD?", back: "Increased TLC and increased residual volume from air trapping." },
  { id: "copd-rt", section: "COPD", front: "What RT interventions matter most in COPD?", back: "Bronchodilators, careful low-flow oxygen, steroids when indicated, rehab, and smoking cessation." },
  { id: "copd-buzzword", section: "COPD", front: "What board clue should make you think emphysema?", back: "Barrel chest with flattened diaphragms and hyperinflation." },
  { id: "copd-comparison", section: "COPD", front: "How does COPD differ from pulmonary fibrosis on tests?", back: "COPD is obstructive with air trapping; fibrosis is restrictive with low lung volumes." },
  { id: "copd-trap", section: "COPD", front: "What is a common exam trap with COPD and oxygen?", back: "Thinking COPD patients should not receive oxygen. They should if hypoxemic, but it should be titrated." },
  { id: "copd-memory", section: "COPD", front: "What quick memory trick helps you remember COPD?", back: "COPD = chronic obstruction plus trapped air." },

  { id: "ards-definition", section: "ARDS", front: "What is ARDS?", back: "Acute inflammatory lung injury causing severe hypoxemia and noncardiogenic pulmonary edema." },
  { id: "ards-causes", section: "ARDS", front: "What commonly triggers ARDS?", back: "Sepsis, trauma, aspiration, pneumonia, pancreatitis, and shock." },
  { id: "ards-symptoms", section: "ARDS", front: "What clinical clues point toward ARDS?", back: "Severe dyspnea, refractory hypoxemia, crackles, and decreased lung compliance." },
  { id: "ards-pf", section: "ARDS", front: "What P/F ratio clue supports ARDS?", back: "A PaO2/FiO2 ratio below 300." },
  { id: "ards-cxr", section: "ARDS", front: "What chest x-ray finding is classic in ARDS?", back: "Bilateral infiltrates with a normal heart size." },
  { id: "ards-vent", section: "ARDS", front: "What ventilator strategy is high-yield for ARDS?", back: "Low tidal volume ventilation with appropriate PEEP and plateau pressure under 30 cmH2O." },
  { id: "ards-prone", section: "ARDS", front: "What adjunct may improve oxygenation in severe ARDS?", back: "Prone positioning." },
  { id: "ards-buzzword", section: "ARDS", front: "What buzzword should immediately make you think ARDS?", back: "Refractory hypoxemia." },
  { id: "ards-comparison", section: "ARDS", front: "How do boards separate ARDS from cardiogenic pulmonary edema?", back: "ARDS is noncardiogenic and classically has a normal heart size on imaging." },
  { id: "ards-trap", section: "ARDS", front: "What is a common exam trap with ARDS management?", back: "Choosing large tidal volumes instead of lung-protective ventilation." },
  { id: "ards-memory", section: "ARDS", front: "What quick memory trick helps you remember ARDS?", back: "ARDS = acute stiff lungs with refractory hypoxemia." },

  { id: "cf-definition", section: "Cystic Fibrosis", front: "What is cystic fibrosis?", back: "A genetic disease that causes abnormal chloride transport and thick mucus." },
  { id: "cf-cause", section: "Cystic Fibrosis", front: "What causes cystic fibrosis?", back: "A CFTR gene mutation." },
  { id: "cf-symptoms", section: "Cystic Fibrosis", front: "What findings are high-yield for cystic fibrosis?", back: "Persistent cough, frequent infections, thick secretions, clubbing, and malnutrition." },
  { id: "cf-diagnostic", section: "Cystic Fibrosis", front: "What test strongly supports cystic fibrosis?", back: "A positive sweat chloride test." },
  { id: "cf-imaging", section: "Cystic Fibrosis", front: "What imaging clues can appear in cystic fibrosis?", back: "Hyperinflation and bronchiectatic changes." },
  { id: "cf-pft", section: "Cystic Fibrosis", front: "What pulmonary function pattern may show up in cystic fibrosis?", back: "Decreased PFT values, often with obstructive changes from mucus plugging." },
  { id: "cf-rt", section: "Cystic Fibrosis", front: "What RT interventions are central in cystic fibrosis?", back: "Airway clearance, bronchodilators, mucolytics like dornase alfa, and hydration support." },
  { id: "cf-buzzword", section: "Cystic Fibrosis", front: "What buzzword pattern should make you think cystic fibrosis?", back: "Thick mucus plus recurrent infections in a younger patient." },
  { id: "cf-comparison", section: "Cystic Fibrosis", front: "How is cystic fibrosis different from simple asthma on exams?", back: "CF centers on secretions and infection; asthma centers on reversible bronchospasm." },
  { id: "cf-trap", section: "Cystic Fibrosis", front: "What is a common exam trap with cystic fibrosis?", back: "Over-focusing on bronchodilators and forgetting airway clearance is the core theme." },
  { id: "cf-memory", section: "Cystic Fibrosis", front: "What quick memory trick helps you remember cystic fibrosis?", back: "CF = chloride problem, thick secretions, constant clearance." },

  { id: "pna-definition", section: "Pneumonia", front: "What is pneumonia?", back: "An alveolar infection that can fill the lungs with fluid or pus." },
  { id: "pna-causes", section: "Pneumonia", front: "What commonly causes pneumonia?", back: "Bacterial, viral, fungal, or aspiration-related infection." },
  { id: "pna-symptoms", section: "Pneumonia", front: "What symptoms are high-yield for pneumonia?", back: "Fever, cough, sputum, dyspnea, pleuritic pain, and crackles." },
  { id: "pna-imaging", section: "Pneumonia", front: "What imaging clue supports pneumonia?", back: "An infiltrate or consolidation on chest x-ray." },
  { id: "pna-lab", section: "Pneumonia", front: "What lab clue often supports pneumonia?", back: "An elevated white blood cell count." },
  { id: "pna-abg", section: "Pneumonia", front: "What ABG concern matters in more severe pneumonia?", back: "Worsening hypoxemia." },
  { id: "pna-rt", section: "Pneumonia", front: "What RT interventions matter most in pneumonia?", back: "Humidified oxygen, airway clearance, hydration support, and close oxygenation monitoring." },
  { id: "pna-buzzword", section: "Pneumonia", front: "What board pattern should make you think pneumonia fast?", back: "Fever plus productive cough plus focal crackles and an infiltrate." },
  { id: "pna-comparison", section: "Pneumonia", front: "How is pneumonia different from pulmonary embolism on exams?", back: "Pneumonia usually has fever, sputum, and infiltrates; PE is more sudden and often has clearer lungs." },
  { id: "pna-trap", section: "Pneumonia", front: "What is a common exam trap with pneumonia?", back: "Confusing it with edema or atelectasis and missing the infectious pattern." },
  { id: "pna-memory", section: "Pneumonia", front: "What quick memory trick helps you remember pneumonia?", back: "Pneumonia = pus, crackles, and infiltrates." },

  { id: "tb-definition", section: "Tuberculosis", front: "What is tuberculosis?", back: "A contagious bacterial infection caused by Mycobacterium tuberculosis." },
  { id: "tb-spread", section: "Tuberculosis", front: "How is tuberculosis transmitted?", back: "Through airborne spread from an infected person." },
  { id: "tb-symptoms", section: "Tuberculosis", front: "What symptoms are high-yield for tuberculosis?", back: "Chronic cough, hemoptysis, night sweats, weight loss, and fever." },
  { id: "tb-diagnostic", section: "Tuberculosis", front: "What tests or findings support tuberculosis?", back: "Positive PPD, cavitary chest x-ray changes, and sputum positive for acid-fast bacilli." },
  { id: "tb-isolation", section: "Tuberculosis", front: "What infection-control setup matters in tuberculosis?", back: "Negative-pressure room with airborne isolation and an N95 mask." },
  { id: "tb-rt", section: "Tuberculosis", front: "What RT role is high-yield in tuberculosis?", back: "Maintain airborne isolation, support oxygenation, and assist with sputum or bronchoscopy workup." },
  { id: "tb-buzzword", section: "Tuberculosis", front: "What board buzzword pattern should make you think tuberculosis?", back: "Cough for more than 3 weeks with night sweats and weight loss." },
  { id: "tb-comparison", section: "Tuberculosis", front: "How is tuberculosis different from pneumonia on exams?", back: "TB is more chronic and often includes cavitations, weight loss, and isolation clues." },
  { id: "tb-trap", section: "Tuberculosis", front: "What is a common exam trap with tuberculosis?", back: "Forgetting infection control and treating it like routine pneumonia." },
  { id: "tb-memory", section: "Tuberculosis", front: "What quick memory trick helps you remember tuberculosis?", back: "TB = cough, cavitation, containment." },

  { id: "pe-definition", section: "Pulmonary Embolism", front: "What is a pulmonary embolism?", back: "A blockage in the pulmonary arteries, usually from a clot that traveled from the legs." },
  { id: "pe-risks", section: "Pulmonary Embolism", front: "What risk factors commonly point toward pulmonary embolism?", back: "Immobility, recent surgery, trauma, and clotting disorders." },
  { id: "pe-symptoms", section: "Pulmonary Embolism", front: "What symptoms are high-yield for pulmonary embolism?", back: "Sudden dyspnea, pleuritic chest pain, tachypnea, tachycardia, and possible hemoptysis." },
  { id: "pe-diagnostic", section: "Pulmonary Embolism", front: "What test is a major diagnostic clue for pulmonary embolism?", back: "CT angiography, with V/Q scan as another common board option." },
  { id: "pe-abg", section: "Pulmonary Embolism", front: "What ABG pattern may appear early in pulmonary embolism?", back: "Hypoxemia with respiratory alkalosis." },
  { id: "pe-lungs", section: "Pulmonary Embolism", front: "What lung exam clue can make pulmonary embolism tricky?", back: "Breath sounds may be normal or nearly normal despite severe dyspnea." },
  { id: "pe-rt", section: "Pulmonary Embolism", front: "What RT interventions matter most in pulmonary embolism?", back: "Give oxygen, monitor vitals closely, and watch for hemodynamic instability." },
  { id: "pe-buzzword", section: "Pulmonary Embolism", front: "What buzzword pattern should make you think pulmonary embolism?", back: "Sudden dyspnea plus postop or immobility history with relatively clear lung sounds." },
  { id: "pe-comparison", section: "Pulmonary Embolism", front: "How is pulmonary embolism different from pneumonia on exams?", back: "PE is sudden with risk factors and often clear lungs; pneumonia is more infectious with crackles and infiltrates." },
  { id: "pe-trap", section: "Pulmonary Embolism", front: "What is a common exam trap with pulmonary embolism?", back: "Picking asthma or pneumonia just because the patient is short of breath." },
  { id: "pe-memory", section: "Pulmonary Embolism", front: "What quick memory trick helps you remember pulmonary embolism?", back: "PE = sudden shortness of breath with a perfusion problem." },

  { id: "pf-definition", section: "Pulmonary Fibrosis", front: "What is pulmonary fibrosis?", back: "A chronic scarring process that makes the lungs stiff and restrictive." },
  { id: "pf-causes", section: "Pulmonary Fibrosis", front: "What can lead to pulmonary fibrosis?", back: "Idiopathic disease, autoimmune conditions, or environmental exposure." },
  { id: "pf-symptoms", section: "Pulmonary Fibrosis", front: "What symptoms are high-yield for pulmonary fibrosis?", back: "Progressive dyspnea, dry cough, fatigue, and clubbing." },
  { id: "pf-imaging", section: "Pulmonary Fibrosis", front: "What imaging clue supports pulmonary fibrosis?", back: "Honeycombing or reticulonodular changes on chest x-ray or CT." },
  { id: "pf-pfts", section: "Pulmonary Fibrosis", front: "What PFT pattern supports pulmonary fibrosis?", back: "Restrictive lung volumes with decreased TLC and decreased DLCO." },
  { id: "pf-rt", section: "Pulmonary Fibrosis", front: "What RT interventions matter in pulmonary fibrosis?", back: "Supplemental oxygen, pulmonary rehab, exertional monitoring, and transplant evaluation support." },
  { id: "pf-buzzword", section: "Pulmonary Fibrosis", front: "What board buzzword should make you think pulmonary fibrosis?", back: "Honeycomb lung with a restrictive pattern and low DLCO." },
  { id: "pf-comparison", section: "Pulmonary Fibrosis", front: "How is pulmonary fibrosis different from COPD?", back: "Fibrosis is restrictive and stiff; COPD is obstructive with trapped air." },
  { id: "pf-trap", section: "Pulmonary Fibrosis", front: "What is a common exam trap with pulmonary fibrosis?", back: "Treating it like reversible obstruction and expecting bronchodilators to fix it." },
  { id: "pf-memory", section: "Pulmonary Fibrosis", front: "What quick memory trick helps you remember pulmonary fibrosis?", back: "Fibrosis = fixed, stiff, and restrictive." },

  { id: "bx-definition", section: "Bronchiectasis", front: "What is bronchiectasis?", back: "Chronic dilation and destruction of the bronchi with mucus retention and repeated infection." },
  { id: "bx-causes", section: "Bronchiectasis", front: "What commonly causes bronchiectasis?", back: "Repeated infections, cystic fibrosis, immune deficiency, and post-infectious airway damage." },
  { id: "bx-symptoms", section: "Bronchiectasis", front: "What symptoms are high-yield for bronchiectasis?", back: "Chronic productive cough, purulent sputum, recurrent infections, crackles, and rhonchi." },
  { id: "bx-diagnostic", section: "Bronchiectasis", front: "What test best confirms bronchiectasis?", back: "Chest CT showing dilated airways." },
  { id: "bx-pft", section: "Bronchiectasis", front: "What pulmonary function pattern may appear in bronchiectasis?", back: "An obstructive pattern can show up because of chronic airway damage and mucus plugging." },
  { id: "bx-rt", section: "Bronchiectasis", front: "What RT interventions matter most in bronchiectasis?", back: "Chest physiotherapy, bronchodilators when needed, mucolytics, hydration, and secretion clearance." },
  { id: "bx-buzzword", section: "Bronchiectasis", front: "What buzzword pattern should make you think bronchiectasis?", back: "Purulent sputum plus recurrent infections plus dilated airways on CT." },
  { id: "bx-comparison", section: "Bronchiectasis", front: "How is bronchiectasis different from simple COPD?", back: "Bronchiectasis is much more centered on chronic infection and heavy secretion burden." },
  { id: "bx-trap", section: "Bronchiectasis", front: "What is a common exam trap with bronchiectasis?", back: "Focusing only on bronchodilators and forgetting secretion clearance is the main theme." },
  { id: "bx-memory", section: "Bronchiectasis", front: "What quick memory trick helps you remember bronchiectasis?", back: "Bronchiectasis = broken bronchi full of mucus." },
];
